Repository portworx/pxdocs, pull requests merged in 2020-01, with the labels that each got.

#603 Reference Architecture Px Secuirty with K8S
  content/cloud-references/security/_index.md
  content/cloud-references/security/kubernetes/_index.md
  content/cloud-references/security/kubernetes/shared-secret-model/_index.md
  content/cloud-references/security/kubernetes/shared-secret-model/enabling-security.md
  content/cloud-references/security/kubernetes/shared-secret-model/example-application.md
  content/cloud-references/security/kubernetes/shared-secret-model/generating-secrets.md
  content/cloud-references/security/kubernetes/shared-secret-model/generating-tokens.md
  content/cloud-references/security/kubernetes/shared-secret-model/storageclass.md
Labels: ready-for-merge

#653 PD-356 Move shared content under a single folder part 10
  content/install-with-other/docker/how-to/volume-plugin.md
  content/key-management/gcloud-kms/pvc-enc/_index.md
  content/key-management/gcloud-kms/shared/_index.md
  content/key-management/gcloud-kms/vol-enc/_index.md
  content/portworx-install-with-kubernetes/cloud/aws/shared/_index.md
  content/portworx-install-with-kubernetes/on-premise/openshift/daemonset/1-prepare.md
  content/portworx-install-with-kubernetes/on-premise/openshift/daemonset/2-deploy-px.md
  content/portworx-install-with-kubernetes/on-premise/openshift/operator/2-deploy-px.md
  content/portworx-install-with-kubernetes/on-premise/openshift/shared/_index.md
  content/portworx-install-with-kubernetes/shared/3-secure-etcd-and-certificates.md
  content/portworx-install-with-kubernetes/shared/_index.md
  content/portworx-install-with-kubernetes/shared/spec-gen-command-line.md
  content/portworx-install-with-kubernetes/storage-operations/create-pvcs/dynamic-provisioning.md
  content/portworx-install-with-kubernetes/storage-operations/create-pvcs/resize-pvc.md
  content/portworx-install-with-kubernetes/storage-operations/create-snapshots/on-demand/snaps-cloud-single.md
  content/portworx-install-with-kubernetes/storage-operations/create-snapshots/on-demand/snaps-cloud.md
  content/portworx-install-with-kubernetes/storage-operations/create-snapshots/on-demand/snaps-group-cloud.md
  content/portworx-install-with-kubernetes/storage-operations/create-snapshots/on-demand/snaps-group.md
  content/portworx-install-with-kubernetes/storage-operations/create-snapshots/on-demand/snaps-local.md
  content/portworx-install-with-kubernetes/storage-operations/create-snapshots/scheduled/_index.md
  content/portworx-install-with-kubernetes/storage-operations/create-snapshots/shared/_index.md
  content/portworx-install-with-kubernetes/storage-operations/create-snapshots/shared/k8s-3d-snap-step-rule.md
  content/portworx-install-with-kubernetes/storage-operations/kubernetes-storage-101/volumes.md
  content/reference/CLI/cloud-snaps.md
  content/reference/CLI/cluster.md
  content/reference/CLI/create-and-manage-volumes.md
  content/reference/CLI/shared/_index.md
  content/reference/CLI/snapshots.md
  content/shared/key-management-gcloud-kms-named-secrets.md
  content/shared/portworx-install-with-kubernetes-on-premise-openshift-1-prepare.md
  content/shared/portworx-install-with-kubernetes-on-premise-openshift-apply-the-spec-oc.md
  content/shared/portworx-install-with-kubernetes-on-premise-openshift-support-notice.md
  content/shared/portworx-install-with-kubernetes-resize-portworx-pvc.md
  content/shared/portworx-install-with-kubernetes-storage-operations-create-snapshots-k8s-cloud-snap-creds-prereq.md
  content/shared/portworx-install-with-kubernetes-storage-operations-create-snapshots-k8s-group-snap-cassandra-step-1-2.md
  content/shared/portworx-install-with-kubernetes-storage-operations-create-snapshots-k8s-group-snap-restore.md
  content/shared/portworx-install-with-kubernetes-storage-operations-create-snapshots-k8s-group-snap-v2-prereqs.md
  content/shared/portworx-install-with-kubernetes-storage-operations-create-snapshots-k8s-restore-pvc-from-snap.md
  content/shared/portworx-install-with-kubernetes-volume-options.md
  content/shared/reference-CLI-creating-snapshots.md
  content/shared/reference-CLI-intro-snapshots.md
  content/shared/reference-CLI-optimized-restores-definition.md
  content/shared/reference-CLI-restore-volume-from-snapshot.md
Labels: ready-for-merge

#331 PD 182 - Reference - Fix keywords
  content/reference/CLI/_index.md
  content/reference/CLI/alerts.md
  content/reference/CLI/authorization.md
  content/reference/CLI/basics.md
  content/reference/CLI/cloud-drives-asg.md
  content/reference/CLI/cloud-migration.md
  content/reference/CLI/cloud-snaps.md
  content/reference/CLI/cluster.md
  content/reference/CLI/create-and-manage-volumes.md
  content/reference/CLI/credentials.md
  content/reference/CLI/encrypted-volumes.md
  content/reference/CLI/group-snaps.md
  content/reference/CLI/license.md
  content/reference/CLI/objectstore.md
  content/reference/CLI/role.md
  content/reference/CLI/service.md
  content/reference/CLI/snapshots.md
  content/reference/CLI/spec-file-generation.md
  content/reference/CLI/storagepolicy.md
  content/reference/CLI/updating-volumes.md
  content/reference/CLI/version-1.2.md
  content/reference/CLI/volume-access.md
  content/reference/Developer SDK/_index.md
  content/reference/REST API/_index.md
  content/reference/_index.md
  content/reference/knowledge-base/_index.md
  content/reference/knowledge-base/etcd-quick-setup.md
  content/reference/knowledge-base/etcd.md
  content/reference/knowledge-base/faqs.md
  content/reference/knowledge-base/network-requirements.md
  content/reference/knowledge-base/px-licensing.md
  content/reference/knowledge-base/supported-kernels.md
  content/reference/lighthouse/_index.md
  content/reference/lighthouse/lighthouse-new-create-credentials.md
  content/reference/lighthouse/lighthouse-snapshots.md
  content/reference/lighthouse/lighthouse-volume-update.md
  content/reference/release-notes/_index.md
  content/reference/release-notes/on-premise-lighthouse.md
  content/shared/reference-CLI-creating-snapshots.md
  content/shared/reference-CLI-intro-snapshots.md
  content/shared/reference-CLI-optimized-restores-definition.md
  content/shared/reference-CLI-restore-volume-from-snapshot.md
Labels: fix-conflicts

#326 PD-182- Cloud references - Fix keywords
  content/cloud-references/_index.md
  content/cloud-references/auto-disk-provisioning/_index.md
  content/cloud-references/auto-disk-provisioning/aws/_index.md
  content/cloud-references/auto-disk-provisioning/gcp/_index.md
  content/cloud-references/auto-disk-provisioning/vsphere/_index.md
  content/cloud-references/cloud-config.md
  content/cloud-references/deployment-arch/_index.md
  content/shared/cloud-references-auto-disk-provisioning-vsphere-vsphere-install-common.md
  content/shared/cloud-references-auto-disk-provisioning-vsphere-vsphere-secret.md
  content/shared/cloud-references-auto-disk-provisioning-vsphere-vsphere-shared-arch.md
Labels: fix-conflicts

#325 PD-182- Concepts - Fix keywords
  content/concepts/_index.md
  content/concepts/authorization/_index.md
  content/concepts/authorization/install.md
  content/concepts/authorization/overview.md
  content/concepts/authorization/pre-install.md
  content/concepts/class-of-service.md
  content/concepts/internal-kvdb.md
  content/concepts/migration.md
  content/concepts/shared-volumes.md
  content/concepts/update-geography-info.md
Labels: fix-conflicts

#324 PD-182- Key management - Fix keywords
  content/key-management/_index.md
  content/key-management/aws-kms/_index.md
  content/key-management/aws-kms/pvc-enc/_index.md
  content/key-management/aws-kms/vol-enc/_index.md
  content/key-management/azure-kv/_index.md
  content/key-management/dc-os-secrets/_index.md
  content/key-management/gcloud-kms/_index.md
  content/key-management/gcloud-kms/pvc-enc/_index.md
  content/key-management/gcloud-kms/vol-enc/_index.md
  content/key-management/ibm-key-protect/_index.md
  content/key-management/ibm-key-protect/pvc-enc/_index.md
  content/key-management/ibm-key-protect/vol-enc/_index.md
  content/key-management/kubernetes-secrets/_index.md
  content/key-management/kubernetes-secrets/pvc-encryption-using-annotations/_index.md
  content/key-management/kubernetes-secrets/pvc-encryption-using-storageclass/_index.md
  content/key-management/vault/_index.md
  content/key-management/vault/pvc-enc/_index.md
  content/key-management/vault/vol-enc/_index.md
  content/shared/key-management-aws-kms-cluster-wide-intro.md
  content/shared/key-management-aws-kms-named-secrets.md
  content/shared/key-management-aws-kms-shared-secure-flag.md
  content/shared/key-management-aws-kms-warning-note.md
  content/shared/key-management-enc-storage-class-spec.md
  content/shared/key-management-gcloud-kms-named-secrets.md
  content/shared/key-management-intro.md
  content/shared/key-management-other-providers-pvc-encryption.md
  content/shared/key-management-per-volume-secret.md
  content/shared/key-management-set-cluster-wide-passphrase.md
  content/shared/key-management-set-cluster-wide-secret.md
  content/shared/key-management-shared-secret-warning-note.md
  content/shared/key-management-storage-class-encryption.md
  content/shared/key-management-volume-cluster-wide-secret.md
Labels: fix-conflicts

#310 add page for pxctl auth
  content/reference/CLI/authorization.md
  content/reference/CLI/self-signed-tokens.md
Labels: fix-conflicts, ready-for-merge
